apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capsule
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-capsule'
    spec:
      project: "platform"
      source:
        repoURL: https://projectcapsule.github.io/charts 
        targetRevision: 0.6.2
        chart: capsule
        helm: {}
      destination:
        server: '{{.server}}'
        namespace: 'capsule-system'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle