apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}-cert-manager'
    spec:
      project: "platform"
      source:
        repoURL: https://charts.jetstack.io
        targetRevision: v1.14.4
        chart: cert-manager
        helm:
          valuesObject:
            installCRDs: true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'cert-manager'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true