apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-sealed-secrets'
    spec:
      project: "platform"
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.15.3
        chart: sealed-secrets
        helm:
          valuesObject:
            fullnameOverride: sealed-secrets-controller
      destination:
        server: '{{.server}}'
        namespace: 'kube-system'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true